//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

namespace GlobalUsingAnalyzer
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalUsingAnalyzer.CodeFixResources", typeof(CodeFixResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to ZGlobalUsings.cs as global using.
        /// </summary>
        internal static string CodeFixTitle
        {
            get
            {
                return ResourceManager.GetString("CodeFixTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to .csproj as &lt;Using /&gt;.
        /// </summary>
        internal static string CodeFixTitleCsproj
        {
            get
            {
                return ResourceManager.GetString("CodeFixTitleCsproj", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to nearest imports file.
        /// </summary>
        internal static string CodeFixTitleImportsRazor
        {
            get
            {
                return ResourceManager.GetString("CodeFixTitleImportsRazor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to nearest _ViewImports.cshtml (GlobalUsingAnalyzer).
        /// </summary>
        internal static string CodeFixTitleViewImportsCshtml
        {
            get
            {
                return ResourceManager.GetString("CodeFixTitleViewImportsCshtml", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to nearest _Imports.razor (GlobalUsingAnalyzer).
        /// </summary>
        internal static string CodeFixTitleImportsRazorFile
        {
            get
            {
                return ResourceManager.GetString("CodeFixTitleImportsRazorFile", resourceCulture);
            }
        }
    }
}
